### PR TITLE
Support F# 5

### LINKED ISSUE #205: FSharp.Core 5.0 support
last version of `Hopac` (0.4.1) depends on `FSharp.Core` (>= 4.5.0 && < 5.0.0)
The command output of `paket outdated` in the project using Hopac looks like this:

```
  Group: Main
    * FSharp.Core 4.7.2 -> 5.0.0
    * Hopac 0.4.1 -> 0.3.23
```

AFAIK Hopac should be compatible with FSharp.Core 5.0.0 also, so the version restriction needs to be relaxed

### PR DESCRIPTION
**Pull request by cmeeren**
Fixes #205

As mentioned in #205 I am unable to build locally, so I don't know whether this will produce the right result.

Please let me know if I should change something else or revert something.

### CODE REVIEW

**Comment by haf** [comment]
What I meant in #205 is that maybe you just set up the scripts / github actions like any other F#/C# project you'd code on? I prefer getting things done, and I'm in no way partial to keeping cygwin-based scripts around. Can't we just have a github action that runs `dotnet restore && dotnet build -c Release && dotnet pack`?

**Comment by cmeeren** [comment]
I've never used GH Actions, only AppVeyor. In any case, if what you are suggesting is that I can just replace the whole build/packaging system in this repo with a simple solution build, no FAKE or other build tools, just `dotnet build` (and VS), then I can probably take a stab at that.

I haven't used `paket` that much in my own projects though. Do you prefer keeping Paket, or are you comfortable with migrating to NuGet?

**Comment by haf** [comment]
Yes, simple is beautiful. But on .Net core so I can run the same command.

I think NuGet is enough for this project because it has basically no dependencies. Just be aware of the combo of Core + Platform in the same package.

**Comment by cmeeren** [comment]
I'll get to it.

> Just be aware of the combo of Core + Platform in the same package.

I don't understand this. Could you elaborate? Two projects in the same NuGet package? I have never done anything like that before and didn't know it was possible.

**Comment by haf** [comment]
Yes, two DLLs in the lib folder.

**Comment by haf** [comment]
You can unzip the existing package to see it.

**Comment by cmeeren** [comment]
Ok. I'll look into it. Another complication is doc generation. I see something called FsiRefGen. Do you need doc generation, or is that legacy? And do you need it as part of the build tools? If so, I think there must be some kind of FAKE script anyway, or if you have other solutions I'm all ears...

**Comment by cmeeren** [comment]
Also, I see that Hopac targets `netstandard2.0` and `net471`. Since `netstandard2.0` is compatible with `net471`, I strongly recommend we only target `netstandard2.0`. Then we can ditch the framework/mono build. If we don't, then I can't help much, because I don't have a mac to test the framework build on. But with ionly `netcoreapp2.0` AFAIK it should "just work".

**Comment by cmeeren** [comment]
Lots of questions now, but I'll ask away: Is `Hopac.snk` and `Hopac.snk.pub` in the repo root necessary, or are they legacy? I have no idea what they are. Some strong-name stuff?

**Comment by cmeeren** [comment]
Last question for tonight: You have mentioned Core and Platform, but what about the project just called "Hopac"?

**Comment by haf** [comment]
> FsiRefGen

This one is actually pretty important, but it's not needed for packaging. It's what generates https://hopac.github.io/Hopac/Hopac.html — it would be good if it can remain for when we add new features or change API:s. It's from https://github.com/polytypic/FsiRefGen

You can get the submodule with `git submodule update --init`.

net471 -> netstandard2.0: sure

Ditch mono, sure. But you can install mono on Windows, so not having a mac is no problem really.

The strong naming keys could remain in the repo. I don't think people use strong naming anymore? But keep them there.

**Comment by haf** [comment]
So, if you read `build.fsx` you see it using https://github.com/Hopac/Hopac/blob/master/Libs/Hopac/Hopac.fsproj.template#L29-L35 to package. It pulls in `.Core` and `.Platform` into `Hopac`; so there are seemingly three DLLs in the package.

**Comment by haf** [comment]
Also, please separate your additions from your deletions, so we can merge additions and solve the problem; then we can go through and look at what to save.

**Comment by HoraceGonzalez** [comment]
If we ditch .net framework, would it make sense to bump the minor version instead of patch? Eg. 0.5 vs 0.4.2?

**Comment by cmeeren** [comment]
> Also, please separate your additions from your deletions

Which deletions? I assume you don't mean everything, since you already said that paket was OK to remove. So some deletions will come as part of the migration; I assume you don't mean those? Nor those that come from removing FAKE (if we do that)?

**Comment by cmeeren** [comment]
> If we ditch .net framework, would it make sense to bump the minor version instead of patch? Eg. 0.5 vs 0.4.2?

I have no strong opinions on the version, but for the sake of my learning, may I ask why? AFAIK the change should be completely transparent, since `netstandard2.0` is compatible with the to-be-dropped `net471`.

**Comment by HoraceGonzalez** [comment]
If the change will be transparent for `net741` users,  then `4.2` makes sense to me, @cmeeren. I wasn't aware that this would be the case.

**Comment by haf** [comment]
I tagged it just now, you can try v0.5

**Comment by haf** [comment]
Thanks to @cmeeren for helping out getting this out of the door!

**Comment by cmeeren** [comment]
@haf You have to update the fsproj version and tag the new commit

image

**Comment by haf** [comment]
Wouldn’t it be possible to take this from the current tag?

**Comment by cmeeren** [comment]
You must make a new commit to update the version, and it is that commit that should be pushed to Nuget, i.e. released. So AFAIK you must make a new tag on that commit.

**Comment by haf** [comment]
I'd rather have the build take it from the env vars, so I don't have to go around updating 10+ files every time — isn't this possible?

**Comment by cmeeren** [comment]
There's only one file, Hopac.fsproj (and RELEASE_NODES.md, but that must of course be done manually anyway).

I see that Hopac.Bench.fsproj and Hopac.Experimental.fsproj also have the current 0.4.1 version, but AFAIK that version is pointless since they aren't released anywhere, so the `Version` tag in those can be removed if you like (or just ignored).

In any case, you may of course set up the build however you like. 👍 I did it the only way I have done myself and the only way I have experience with, which is do make AppVeyor publish the created NuGet package after building tagged commits, if the version (set in the `fsproj`) does not already exist on NuGet.

**Comment by haf** [comment]
Thank you @cmeeren , I did this and there should be a new release out.

**Comment by cmeeren** [comment]
Seems you forgot to tag the commit (or push the tag to GH), so AppVeyor didn't push the package to NuGet.

**Comment by cmeeren** [comment]
The new version is pushed now and seems to work fine. Thanks! 👍

**Pull request closed without merging**
