### PR TITLE
Some dotnetcore work

### PR DESCRIPTION
**Pull request by enricosada**
- fixing project2project ref, the name of directory should be the same of package/assembly ( `Libs/Hopac.Platform` for dotnetcore )
- cleanup project.json
- add a benchmarkdotnet benchmark project
- compile `net46` too with .net core sdk toolchain
- support both `net46` and netcoreapp1.0` in `benchmark/Fibonacci`

### CODE REVIEW

**Comment by haf** [comment]
@enricosada Thank you!

**Comment by ncave** [comment]
@enricosada Re: "name of directory should be the same of assembly for dotnetcore":
Is that really a requirement, what is the purpose of the "name" attribute then? Or is it just a work-around for the tooling issue that the build does not get triggered? Cause everything else works, the correct binary as defined in the "name" attribute will be copied, it just doesn't trigger the build. If it's not a requirement, perhaps we can open a tooling issue (even though the project.json is going away, but who knows when).

**Comment by enricosada** [comment]
@ncave it's just a tooling bug, but it's too annoying i think to not workaround. Using an not up-to-date assembly cause lot of dev pain.
I strongly avoid that property, i trust only the directory name, because create issue with `dotnet run`, `dotnet test` `dotnet pack` too (for example wrong package reference in generated nuspec from `dotnet pack`).

ref dotnet/cli#3040 or dotnet/cli#3183 and dupes, there is a better issue but i cannot find it. It's not going to be fixed, because of the move from `project.json` => `msbuild` in next `preview3` (from a dotnet/cli team comment)

**Comment by ncave** [comment]
Thanks for looking it up @enricosada!

**Pull request merged**
