### PR TITLE
Sig rethink

### PR DESCRIPTION
**Pull request by polytypic**

### CODE REVIEW

**Comment by haf** [comment]
Is this towards 1.0? *hoping so*

**Comment by vasily-kirichenko** [comment]
Looks great.

**Comment by polytypic** [comment]
@haf  I'm thinking of making the next version number to 0.1.0.  There are a couple of bigger things I'd like to resolve before 1.0.0.  Whether I have enough time to do those is another matter.

**Comment by vasily-kirichenko** [comment]
"No lisp" is awesome :)

**Comment by polytypic** [comment]
@vasily-kirichenko Heh... :)

**Comment by vasily-kirichenko** [comment]
Should I publish a new nuget?

**Comment by polytypic** [comment]
Not yet.  I plan to do a little bit more work on Hopac this weekend.

**Pull request merged**
