### PR TITLE
Simplify build/pack

### PR DESCRIPTION
**Pull request by cmeeren**
It now builds and packs fine with `dotnet build` and VS (NuGet package automatically generated on build).

Notes:
* AppVeyor will push tagged commits to NuGet. But first, in `appveyor.yml`, replace `MY_SECRET_KEY_HERE` with the encrypted NuGet key. To encrypt strings, sign in to AppVeyor with the account that builds the project and go to https://ci.appveyor.com/tools/encrypt.
* Updating the docs is not something I have looked into, nor am I particularly concerned about that at the moment (or can prioritize delving into it). I have left a `TODO` in the readme where the instructions should be.
* I know nothing about signing assemblies or whether the existing NuGet package has signed assemblies. I don't think any assemblies are signed with the build system in this PR.
* I removed the travis build since it seems that it (or the AppVeyor build) hasn't been used in ages. We don't need multiple builds anyway since it builds with .NET Core. I simplified the AppVeyor build to work as described above. Note that no tests are run as part of CI because there doesn't seem to be any test projects (hence `dotnet test` doesn't do anything).
* The resulting nupkg looks very much like the existing one on NuGet, except that the version restriction is relaxed. But please verify before publishing the first version with this new system.

Let me know if I should change anything, but please note that I have limited resources to spend, so as much as I'm a perfectionist normally, here I'd like to focus on what is specifically needed for pushing a new version with relaxed FSharp.Core version requirements, and leave it there.

### CODE REVIEW

**Comment by haf** [comment]
Let's merge and see how AppVeyor reacts.

**Comment by cmeeren** [comment]
Seems to have gone well. I don't know if you're familiar with AppVeyor, but you can get the generated nupkg here: https://ci.appveyor.com/project/haf/hopac/build/artifacts

**Comment by haf** [comment]
Maybe we bump to v0.5 now and someone could verify the packages? Then I can push those.

**Comment by vilinski** [comment]
@cmeeren @haf downloaded and tried it out. Included dlls are working like a charm in the `dotnet fsi`.
nuspec file looks also correct

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Hopac</id>
    <version>0.4.1</version>
    <authors>Vesa Karvonen</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <license type="expression">MIT</license>
    <licenseUrl>https://licenses.nuget.org/MIT</licenseUrl>
    <icon>logo.png</icon>
    <projectUrl>https://github.com/Hopac/Hopac</projectUrl>
    <description>Hopac is a library for higher-Order, parallel, asynchronous and concurrent programming in F#.

Inspired by languages like Concurrent ML and Cilk, Hopac is a library for F# with the aim of making it easier to write efficient parallel, asynchronous, concurrent and reactive programs. Hopac is licensed under a MIT-style license. See project website for further information.</description>
    <copyright>© 2016 Vesa Karvonen, 2018 Open Source Contributors</copyright>
    <tags>F# documentation fsi html</tags>
    <repository url="https://github.com/Hopac/Hopac" />
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="FSharp.Core" version="4.5.2" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

**Comment by cmeeren** [comment]
@vilinski Happy to hear it! Looking forward to release.

@haf, Do you want to do it yourself, or do you prefer a PR to bump versions and update release notes? (You need to tag the commit anyway, a PR can't do that.)

**Pull request merged**
