### PR TITLE
Feature/strong naming mono

### PR DESCRIPTION
**Pull request by haf**
We triggered mono beta-releases regression, see https://bugzilla.xamarin.com/show_bug.cgi?id=40862 but 'latest' and '4.0.0' work.

### CODE REVIEW

**Comment by haf** [comment]
Sending from @haf account instead.

**Comment by haf** [comment]
With the call to the benchmark here https://travis-ci.org/Hopac/Hopac/jobs/128821356#L1758 travis reproduces the error.

**Comment by haf-raysearchlabs** [comment]
@polytypic I think we should merge this so that compilation works on Windows again.

Then me and Andreas will ensure it's conditionally compilable so that we can at least use non-signed dlls on Mono.

**Comment by polytypic** [comment]
Ok.

**Pull request merged**
